# @author ruslan007
# @date 13.03.2015
#
#
#
#
NEW:
    name: ""
    permission: "all allow"
    pages:
        bb.project.orders.actionOrders.toEnd: "deny"
        bb.project.orders.actionOrders.backToFill: "deny"
        bb.project.orders.actionOrders.pay: "deny"
        bb.project.orders.actionOrders.toReSign: "deny"
        bb.project.orders.actionOrders.debit: "deny"
        bb.project.orders.actionOrders.freeAnnul: "deny"
        bb.project.orders.signOrders.signOff1: "deny"
        bb.project.orders.signOrders.signOff2: "deny"
        bb.project.orders.signOrders.infoOffTel1.sign: "deny"
        bb.project.orders.signOrders.infoOffTel2.sign: "deny"
        bb.project.orders.viewOrders.approvedOrderSum: "deny"
        bb.project.orders.viewOrders.payedOrderSum: "deny"
        bb.project.orders.viewOrders.receivedOrderSum: "deny"
        bb.project.orders.viewOrders.print: "deny"
APPROVING:
    name: ""
    permission: "all allow"
    pages:
        bb.project.orders.actionOrders.toSign: "deny"
        bb.project.orders.actionOrders.toEnd: "deny"
        bb.project.orders.actionOrders.pay: "deny"
        bb.project.orders.actionOrders.toReSign: "deny"
        bb.project.orders.actionOrders.debit: "deny"
        bb.project.orders.actionOrders.freeAnnul: "deny"
        bb.project.orders.viewOrders.approvedOrderSum: "deny"
        bb.project.orders.viewOrders.payedOrderSum: "deny"
        bb.project.orders.viewOrders.receivedOrderSum: "deny"
        bb.project.orders.viewOrders.edit.orderNDS: "deny"
        bb.project.orders.viewOrders.edit: "deny"
APPROVED:
    name: ""
    permission: "all allow"
    pages:
        bb.project.orders.actionOrders.toSign: "deny"
        bb.project.orders.actionOrders.toEnd: "deny"
        bb.project.orders.actionOrders.freeAnnul: "deny"
        bb.project.orders.actionOrders.annul: "deny"
        bb.project.orders.signOrders.infoOffTel1.sign: "deny"
        bb.project.orders.signOrders.infoOffTel2.sign: "deny"
        bb.project.orders.viewOrders.payedOrderSum: "deny"
        bb.project.orders.viewOrders.receivedOrderSum: "deny"
        bb.project.orders.viewOrders.edit.orderNDS: "deny"