# @author ruslan007
# @date 13.03.2015
#
#
#
#
#
#
NEW:
    name: ""
    permission: "all allow"
    pages:
        bb.project.projSettings.labels: "deny"
        bb.project.projSettings.toPreapprove: "deny"
        bb.project.projSettings.backToChange: "deny"
        bb.project.projSettings.preapprove: "deny"
        bb.project.projSettings.approve: "deny"
        bb.project.projSettings.backToApprove: "deny"
        bb.project.projSettings.toRun: "deny"
        bb.project.projSettings.toFinish: "deny"
        bb.project.projSettings.startDate: "deny"
        bb.project.projSettings.endDate: "deny"
        bb.project.budget.edit.addRows.showAtationAdd: "deny"
        bb.project.orders: "deny"
        bb.project.money: "deny"
PREFORMED:
    name: ""
    permission: "all deny"
    pages: