# list of permissions for users
# @author ruslan007
# @date 13.03.2015
#
#
#
#
#
#
#
ADMIN:
    name: ""
    permission: "all allow"
    pages:
        bb.project.orders.signOrders.signOff1: "deny"
        bb.project.orders.signOrders.signOff2: "deny"
        bb.project.orders.signOrders.infoOffTel1.sign: "deny"
        bb.project.orders.signOrders.infoOffTel2.sign: "deny"

LDC:
    name: ""
    permission: "all allow"
    pages:
        bb.project.orders.signOrders.signOff1: "deny"
        bb.project.orders.signOrders.signOff2: "deny"
        bb.project.orders.signOrders.infoOffTel1.sign: "deny"
        bb.project.orders.signOrders.infoOffTel2.sign: "deny"
USER:
    name: ""
    permission: "all deny"
    pages: []

BK:
    name: ""
    permission: "all deny"
    pages:
        bb.projects.materials: "allow"
        bb.projects.suppliers.edit: "allow"
        bb.project.budget: "allow"
        bb.project.orders.createOrders: "allow"
        bb.project.orders.viewOrders: "allow"
        bb.project.orders.actionOrders: "allow"
        bb.project.orders.export: "allow"
        bb.project.orders.signOrders.infoOffTel1: "allow"
        bb.project.orders.signOrders.infoOffTel2: "allow"
        bb.project.money: "allow"
########AND OTHER